pipeline {
  agent any

  stages{

    stage('Build Jar'){
        steps{
            sh "mvn clean package -DskipTests"
        }
    }

    stage('Build Image'){
        steps{
            sh "docker build -t=mzcoder7/selenium-docker ."
        }
    }

    stage('Push Image'){
        steps{
            echo "docker push mzcoder7/selenium-docker"
        }
    }
  }
}